application: super-tower
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: pixi.js-3.0.8

- url: /img
  static_dir: img

- url: .*
  script: main.php
